### PR TITLE
Support for Hierarchical query. This patch adds the support for the h…

### PR DESCRIPTION
**Pull request by rasifr**
Support for Hierarchical query. This patch adds the support for the hierarchical
    query by transforming a Hierarchical Select query on to a Common Table Expression
    (CTE). This implementation includes hierarchical query syntax and in addition to
    that following pseudo/special columns as well:
            - PRIOR
            - LEVEL
            - CONNECT_BY_ROOT
            - SYS_CONNECT_BY_PATH
    
    Limitations:
    Currently this feature has the following limitations.
    - The additional columns can be used in most expression like function call, CASE
      statement and common expression, however there are few that are not supported
      like ROW, TYPECAST, COLLATE, GROUPING clauses etc.
    -  an output column name may be needed in some cases where two or more column
       are identical like
        SELECT CONNECT_BY_ROOT col AS "col1", CONNECT_BY_ROOT col AS "col2" ....
    - Indirection operator or '*' is not supported.
    - Loop detection is not supported.

### CODE REVIEW

**Comment by rasifr** [comment]
submitted previously as PR https://github.com/IvorySQL/IvorySQL/pull/32 , which got closed accidentally and the branch was updated. so submitting as new PR after resolving the review comments.

**Comment by KingZhaoTPG** [comment]
Hi @rasifr , I use a small test case to test this feature. It doesn't seem to work well for CONNECT_BY_ROOT columns. My TC is shown below, please check it. thanks!

```
CREATE TABLE t_tab (
     id     int, 
    manager_id  int
);
INSERT INTO t_tab VALUES (1, 0);
INSERT INTO t_tab VALUES (2, 1);
INSERT INTO t_tab VALUES (3, 2);

hges_test=# select
hges_test-#  connect_by_root manager_id,id,SYS_CONNECT_BY_PATH(id, '\') PATH
hges_test-#  from t_tab
hges_test-#  start with manager_id = 1
hges_test-#  connect by prior id = manager_id;
**ERROR**:  column cte_t_tab.manager_id does not exist
LINE 2:  connect_by_root manager_id,id,SYS_CONNECT_BY_PATH(id, '\') ...
                         ^
hges_test=#
hges_test=#
hges_test=# select
hges_test-#  manager_id,id,SYS_CONNECT_BY_PATH(id, '\') PATH
hges_test-#  from t_tab
hges_test-#  start with manager_id = 1
hges_test-#  connect by prior id = manager_id;
 manager_id | id | path
------------+----+------
          1 |  2 | \2
          2 |  3 | \2\3
(2 rows)

```

**Comment by KingZhaoTPG** [comment]
Hi @rasifr , I tested your latest PR. I found the following other issues, pls check it again. Thanks!

```
-- My TC
DROP TABLE entities;
CREATE TABLE entities(
    parent_entity varchar(20),
    child_entity varchar(20),
    val int
);
Insert into entities (parent_entity, child_entity,val) values (NULL,'a',100);
Insert into entities (parent_entity, child_entity,val) values ('a', 'af',50);
Insert into entities (parent_entity, child_entity,val) values ('a', 'ab',50);
Insert into entities (parent_entity, child_entity,val) values ('a', 'ax',50);
Insert into entities (parent_entity, child_entity,val) values ('ab', 'abc',10);
Insert into entities (parent_entity, child_entity,val) values ('ab', 'abd',10);
Insert into entities (parent_entity, child_entity,val) values ('ab', 'abe',10);
Insert into entities (parent_entity, child_entity,val) values ('abe', 'abes',1);
Insert into entities (parent_entity, child_entity,val) values ('abe', 'abet',1);
Insert into entities (parent_entity, child_entity,val) values (NULL,'b',100);
Insert into entities (parent_entity, child_entity,val) values ('b', 'bg',50);
Insert into entities (parent_entity, child_entity,val) values ('b', 'bh',50);
Insert into entities (parent_entity, child_entity,val) values ('b', 'bi',50);
Insert into entities (parent_entity, child_entity,val) values ('bi', 'biq',10);
Insert into entities (parent_entity, child_entity,val) values ('bi', 'biv',10);

--SQL statement
select parent_entity, child_entity 
 from entities
 connect by prior child_entity = parent_entity order by val;

-- Error report
hges_test=# select parent_entity, child_entity
hges_test-#  from entities
hges_test-#  connect by prior child_entity = parent_entity order by val;
ERROR:  column "val" does not exist
LINE 3:  connect by prior child_entity = parent_entity order by val;

-- SQL statement
select parent_entity, child_entity 
 from entities
 connect by prior child_entity = parent_entity and prior val = 50;

-- Error report, Oracle supports multiple PRIOR
hges_test=# select parent_entity, child_entity
hges_test-#  from entities
hges_test-#  connect by prior child_entity = parent_entity and prior val = 50;
ERROR:  column cte_entities.val does not exist
LINE 3: ...ct by prior child_entity = parent_entity and prior val = 50;

-- Test loop
-- there may be a possibility if the hierarchal data contains a loop.
-- the below insert statement on entities table:
Insert into entities (parent_entity, child_entity,val) values ('abet', 'a',101);

-- If you execute the below query
select parent_entity, child_entity
 from entities
 start with parent_entity is NULL
 connect by prior child_entity = parent_entity;

-- Oracle will report an error :
ORA-01436: CONNECT BY loop in user data
01436. 00000 -  "CONNECT BY loop in user data"

-- In IvorySQL, the server will hang......
```

**Comment by KingZhaoTPG** [comment]
Hi @rasifr , The order by clause seems ok and works well. but there are still exists some issues as following. Could you please check it again?

```
hges_test=#
hges_test=# select * from entities
 connect by prior child_entity = parent_entity order by val;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?> \q
[hges_zhao@192 myHges]$
[hges_zhao@192 myHges]$
[hges_zhao@192 myHges]$ psql -d hges_test;
psql (15devel)
Type "help" for help.

hges_test=# select entities.* from entities
 connect by prior child_entity = parent_entity order by val;
ERROR:  missing FROM-clause entry for table "entities"
LINE 1: select entities.* from entities
               ^
hges_test=#
```

**Comment by rasifr** [comment]
@KingZhaoTPG tested the updated PR and his tests worked, except for related to the limitations. So we merged this PR.

**Pull request merged**
