### PR TITLE
Fix: Support for SYSDATE & SYSTIMESTAMP

### PR DESCRIPTION
**Pull request by imranzaheer612**
- Add defination for SYSDATE in oracle parser
- Add defination for SYSTIMESTAMP in oracle parser

### CODE REVIEW

**Comment by imranzaheer612** [comment]
Pull request is related to the issue https://github.com/IvorySQL/IvorySQL/issues/633

**Comment by imranzaheer612** [comment]
Pull request is also related to the issue https://github.com/IvorySQL/IvorySQL/issues/661

**Comment by bigplaice** [comment]
Hi, Imran,

Thanks for your contribution to IvorySQL! 
Some comments as below:

1. Add SYSDATE and SYSTIMESTAMP to the bare_label_keyword section and type_func_name_keyword section of ora_gram.y, otherfwise the build would fail.
2. Add regress test case for the introduced new functionality. May find a appropriate file in src/oracle_test/regress/sql
3. Please run CI on your local repositary and make sure no failure before submit of PR. Note we just fixed a build issue on master branch, so you need update your local master branch to sync with ours.

Any question, please feel free to contact us. 

Regards,
Steven

@imranzaheer612

**Comment by imranzaheer612** [comment]
Ok thanks for the explanation @bigplaice . I will try fixing it.

**Comment by gaoxueyu** [comment]
Thanks Imran.
I'll close this PR for now. Looking forward to your submission of a new PR.

**Pull request closed without merging**
